### ISSUE TITLE
EB Project Editor Malfunction [Linux]

### ISSUE THREAD

**Issue by werty534tm** [pk-hack/CoilSnake#305]
Loading a project with the Project Editor throws a java exception:
java.io.FileNotFoundException: /home/jose/CoilSnake/HelloWorld/null (No existe el fichero o el directorio)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
	at ebhack.MapEditor$MapData.importNPCs(MapEditor.java:2127)
	at ebhack.MapEditor$MapData.loadExtraResources(MapEditor.java:1967)
	at ebhack.MapEditor$MapData.load(MapEditor.java:1963)
	at ebhack.MapEditor.load(MapEditor.java:2823)
	at ebhack.MainGUI.loadModulesData(MainGUI.java:322)
	at ebhack.MainGUI.loadProject(MainGUI.java:444)
	at ebhack.MainGUI.loadProject(MainGUI.java:468)
	at ebhack.MainGUI.access$500(MainGUI.java:14)
	at ebhack.MainGUI$2.doInBackground(MainGUI.java:607)
	at ebhack.MainGUI$2.doInBackground(MainGUI.java:602)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:305)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:342)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

The spanish text in the exception translates as "the file or directory does not exist".

It lets me open the map editor anyway, but there are no entities, persons, objects or whatever they are called.
If I then change to sprite editor mode (F2) and click any tile, java throws another exception and does nothing.

The exception:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read field "sprite" because "npc" is null
	at ebhack.MapEditor$MapData.popNPCFromCoords(MapEditor.java:2016)
	at ebhack.MapEditor$MapDisplay.popNpcIdFromMouseXY(MapEditor.java:1274)
	at ebhack.MapEditor$MapDisplay.mousePressed(MapEditor.java:1357)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6618)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Im sorry for the awful format of this issue. I am not used to markdown.

**Comment by PhoenixBound** [comment]
It looks like the current version of CoilSnake is not compatible with the current version of EB Project Editor, by accident (or the slightly out of date version that CoilSnake bundles): pk-hack/EbProjectEditor#20. The latest version of CoilSnake moved where the code that handles the NPC config table is to a different Python file, and project.snake has to know about it, and EB Project Editor opens projects the "correct" way by going through project.snake to get the file name.

Until this issue is resolved, you can work around it by explicitly checking out the `v4.2` tag with `git checkout tags/v4.2` and decompiling the project again. Things are kind of in flux between versions right now, and we haven't fully updated everything to properly mark itself as incompatible with CoilSnake 4.2 or have proper tool support.

With regard to Markdown, you can put something in a code block on GitHub by putting three grave accents \`\`\` at the beginning and end of it. On a US QWERTY keyboard, this key is to the left of the `1`; on a Latin American Spanish keyboard, it's on the same key as `]}` when you use AltGr; on a Spain Spanish keyboard, it looks like that symbol is available as a dead key to the right of `P`?
